package com.zein;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class PenguranganTest {

        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @Before
        public void setUp() {
            System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "\\driver\\chromedriver.exe");
            driver = new ChromeDriver();
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
        @After
        public void tearDown() {
            driver.quit();
        }
        @Test
        public void case1() {
            driver.get("https://greyli.github.io/calculator/");
            driver.manage().window().setSize(new Dimension(651, 616));
            driver.findElement(By.xpath("//button[@value=\'9\']")).click();
            driver.findElement(By.xpath("//button[@value=\'9\']")).click();
            driver.findElement(By.xpath("//button[@value=\'-\']")).click();
            driver.findElement(By.xpath("//button[@value=\'9\']")).click();
            driver.findElement(By.xpath("//button[@value=\'8\']")).click();
            driver.findElement(By.xpath("//button[@id=\'resultButton\']")).click();
            assertThat(driver.findElement(By.xpath("//div[@id=\'output\']")).getText(), is("1"));
            driver.close();
        }
    }



